dbt_cloud_oct:
  outputs:
    dev:
      account: MWB11869
      database: ANALYTICS
      password: Sachin$123
      role: analyticsengineer
      schema: DBT_G_DBT
      threads: 3
      type: snowflake
      user: sachin
      warehouse: transform_wh
  target: dev



