sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: nations
      - name: regions
      - name: v_nations
      - name: lineitems
      - name: parts
      - name: suppliers
      - name: orders
      
        config:
          freshness:
            warn_after: {count: 1, period: hour}
            error_after: {count: 1, period: hour}
          loaded_at_field: o_orderdate::timestamp_ntz

  - name: src_1
    database: MKMOTORS_DEV
    schema: STAGING
    tables:
      - name: STG_EMPLOYEES
      - name: STG_DATES
  
  - name: src_2
    database: MKMOTORS_DEV
    schema: DW
    tables:
      - name: DM_DATES